# Site settings
title: Stacy Zolnikov
email: zolnikovstacy@gmail.com
url: https://example.github.io
description: "I'm a thinker and a doer - I come up with solutions to problems (and sometimes solve for problems that don't even exist).  Because I'm curious by nature and ask a lot of questions, I've mastered the art of Googling which has made me an expert of on a variety of topics like eCommerce, foreign affairs and more recently, Android Development. 

I'm fluent in Italian and Russian, have travelled over the world and have extensive knowledge in foreign affairs, international relations, human intelligence, world economics, diplomacy and humanitarian aid.  

Some of my personal hobbies include: riding motorcycles, scuba diving, producing music, running marathons, traveling and coming up with entrepreneurial, world-changing ideas."
skills: "Android Developer - Gymnastics Coach - Perpetual Learner - Adventure Seeker "
meta_author: Zolnikov, Stacy

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Stacy Zolnikov
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: http://linkedin.com/in/stacyzolnikov
  - title: facebook
    url: https://www.facebook.com/stacy.zolnikov
  - title: github
    url: https://github.com/StacyZol

# Postal address (add as many lines as necessary)
address:
  - line: New York, NY

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
